#!/usr/bin/env python3
"""
Regenerate Swift baselines for the Whisper text normalizer.

What this script writes
-----------------------
1. `Sources/Tokenizers/EnglishSpellingTable.swift`
   - Swift source file containing the British→American spelling mapping
     used by `EnglishSpellingNormalizer`. The mapping is pulled from
     `openai/whisper`'s `english.json` (the canonical reference).
2. `Tests/TokenizersTests/Resources/whisper-normalizer-baselines.json`
   - JSON fixture pairing each curated input with the expected output of
     `BasicTextNormalizer` (in three configurations) and
     `EnglishTextNormalizer`, as produced by the pinned `transformers`
     release. The Swift test target reads this fixture and asserts
     byte-identical parity.

How to run
----------
    cd swift-transformers
    python3 -m venv .venv-whisper-normalizer
    source .venv-whisper-normalizer/bin/activate
    pip install -r Tools/requirements.txt
    python Tools/generate_whisper_normalizer_baselines.py

The script is idempotent: running it without source changes produces
identical files.
"""
from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path
from textwrap import dedent

from whisper_normalizer_inputs import CORPUS

ENGLISH_JSON_URL = (
    "https://raw.githubusercontent.com/openai/whisper/main/whisper/normalizers/english.json"
)

REPO_ROOT = Path(__file__).resolve().parent.parent
SPELLING_TABLE_SWIFT = REPO_ROOT / "Sources/Tokenizers/EnglishSpellingTable.swift"
BASELINES_JSON = (
    REPO_ROOT / "Tests/TokenizersTests/Resources/whisper-normalizer-baselines.json"
)


def fetch_spelling_mapping() -> dict[str, str]:
    """Download the canonical British→American mapping from openai/whisper."""
    with urllib.request.urlopen(ENGLISH_JSON_URL) as resp:
        return json.loads(resp.read().decode("utf-8"))


def swift_escape(s: str) -> str:
    """Escape a Python string for inclusion in a Swift string literal."""
    out = []
    for c in s:
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        else:
            out.append(c)
    return "".join(out)


def write_spelling_table(mapping: dict[str, str], path: Path) -> None:
    entries = sorted(mapping.items())
    header = dedent(
        """\
        // This file is auto-generated by Tools/generate_whisper_normalizer_baselines.py.
        // Do not edit by hand. Source of truth:
        // https://raw.githubusercontent.com/openai/whisper/main/whisper/normalizers/english.json

        /// British→American spelling mapping used by `EnglishSpellingNormalizer`.
        /// Each entry maps a British spelling to its American counterpart; words
        /// not present in the table are passed through unchanged.
        public let englishSpellingTable: [String: String] = [
        """
    )
    body_lines = [
        f'    "{swift_escape(k)}": "{swift_escape(v)}",' for k, v in entries
    ]
    footer = "]\n"
    path.write_text(header + "\n".join(body_lines) + "\n" + footer, encoding="utf-8")
    print(f"wrote {path.relative_to(REPO_ROOT)} ({len(entries)} entries)")


def write_baselines(mapping: dict[str, str], path: Path) -> None:
    # Local import so the script can fail early with a clear message if the
    # pinned transformers release is missing.
    try:
        from transformers.models.whisper.english_normalizer import (
            BasicTextNormalizer,
            EnglishTextNormalizer,
        )
    except ImportError as exc:
        print(
            "transformers is required. Install with: "
            "pip install -r Tools/requirements.txt",
            file=sys.stderr,
        )
        raise SystemExit(1) from exc

    basic_plain = BasicTextNormalizer()
    basic_diacritics = BasicTextNormalizer(remove_diacritics=True)
    basic_split = BasicTextNormalizer(split_letters=True)
    english = EnglishTextNormalizer(mapping)

    fixtures = []
    for case_id, text in CORPUS:
        fixtures.append(
            {
                "id": case_id,
                "input": text,
                "basic": basic_plain(text),
                "basic_remove_diacritics": basic_diacritics(text),
                "basic_split_letters": basic_split(text),
                "english": english(text),
            }
        )

    import transformers

    payload = {
        "_meta": {
            "source": "transformers.models.whisper.english_normalizer",
            "transformers_version": transformers.__version__,
            "english_json_url": ENGLISH_JSON_URL,
            "regenerate_with": "python Tools/generate_whisper_normalizer_baselines.py",
        },
        "fixtures": fixtures,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {path.relative_to(REPO_ROOT)} ({len(fixtures)} cases)")


def main() -> int:
    mapping = fetch_spelling_mapping()
    write_spelling_table(mapping, SPELLING_TABLE_SWIFT)
    write_baselines(mapping, BASELINES_JSON)
    return 0


if __name__ == "__main__":
    sys.exit(main())
